import { Ionicons } from '@expo/vector-icons';
import { useCallback } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { OrderCard } from '@/components/OrderCard';
import { Screen } from '@/components/Screen';
import { useDelivery } from '@/context/DeliveryContext';
import { colors, radius, spacing } from '@/theme';

export default function Assignments(){const{user,orders,loading,refresh}=useDelivery();const active=orders.filter(o=>!['DELIVERED','CANCELLED'].includes(o.status));const reload=useCallback(()=>{refresh().catch(()=>undefined)},[refresh]);return <Screen><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={reload} tintColor={colors.forest}/>} contentContainerStyle={styles.content}>
  <View style={styles.header}><View><Text style={styles.hello}>Namaste, {user?.name?.split(' ')[0] ?? 'Partner'} 👋</Text><Text style={styles.sub}>Your delivery command centre</Text></View><View style={styles.online}><View/><Text>ONLINE</Text></View></View>
  <View style={styles.routeHero}><View><Text style={styles.eyebrow}>TODAY’S ROUTE</Text><Text style={styles.big}>{active.length}</Text><Text style={styles.label}>active deliveries</Text></View><View style={styles.scooter}><Ionicons name="bicycle" size={40} color={colors.forest}/></View><View style={styles.routeLine}/></View>
  <View style={styles.stats}><View><Ionicons name="cube" size={17} color={colors.orange}/><Text><Text style={styles.strong}>{orders.length}</Text>{'\n'}assigned</Text></View><View><Ionicons name="checkmark-done" size={17} color={colors.leaf}/><Text><Text style={styles.strong}>{orders.filter(o=>o.status==='DELIVERED').length}</Text>{'\n'}completed</Text></View><View><Ionicons name="cash" size={17} color={colors.gold}/><Text><Text style={styles.strong}>{orders.filter(o=>o.paymentMethod==='COD'&&o.status!=='DELIVERED').length}</Text>{'\n'}COD stops</Text></View></View>
  <View style={styles.sectionTitle}><Text>Assigned orders</Text><Text>{active.length} stops</Text></View>{loading&&!orders.length?<ActivityIndicator color={colors.forest}/>:active.length?active.map(order=><OrderCard order={order} key={order.id}/>):<View style={styles.empty}><Text>🎉</Text><Text style={styles.emptyTitle}>All caught up!</Text><Text style={styles.emptyBody}>New assignments will appear here automatically.</Text></View>}
  <View style={{height:20}}/></ScrollView></Screen>}
const styles=StyleSheet.create({content:{padding:spacing.lg,gap:spacing.md},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:spacing.sm,marginBottom:spacing.sm},hello:{fontSize:20,fontWeight:'900',color:colors.ink},sub:{fontSize:10,color:colors.muted,marginTop:3},online:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:colors.paleGreen,paddingHorizontal:9,paddingVertical:6,borderRadius:radius.pill},onlineDot:{},onlineText:{},routeHero:{height:155,borderRadius:radius.xl,backgroundColor:colors.forest,padding:spacing.xl,overflow:'hidden',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},eyebrow:{color:'#AFC8B7',fontSize:8,letterSpacing:1.6,fontWeight:'900'},big:{color:'white',fontSize:43,fontWeight:'900',lineHeight:48},label:{color:'#C7D8CC',fontSize:11},scooter:{width:75,height:75,borderRadius:25,backgroundColor:colors.gold,alignItems:'center',justifyContent:'center',zIndex:2},routeLine:{position:'absolute',height:110,width:280,borderWidth:1,borderColor:'#ffffff18',borderRadius:120,right:-80,top:24},stats:{flexDirection:'row',backgroundColor:colors.white,borderRadius:radius.lg,borderWidth:1,borderColor:colors.line,padding:spacing.md},statsRow:{},statsText:{},strong:{fontSize:15,fontWeight:'900',color:colors.ink},sectionTitle:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:spacing.md},sectionTitleText:{},empty:{alignItems:'center',padding:spacing.xxxl,backgroundColor:colors.white,borderRadius:radius.lg,borderWidth:1,borderColor:colors.line},emptyTitle:{fontSize:16,fontWeight:'900',color:colors.ink,marginTop:spacing.sm},emptyBody:{fontSize:10,color:colors.muted,marginTop:4}});
